---
title: "co-occurrence network in feather samples"
author: "Zhu Ying"
date: "2023-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R packages

```{r}
local({r <- getOption("repos")  
r["CRAN"] <- "http://mirrors.tuna.tsinghua.edu.cn/CRAN/"   
r["BioC_mirror"] <- "https://mirrors.tuna.tsinghua.edu.cn/bioconductor"
options(repos=r)}) 


if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

a = rownames(installed.packages())

install_package <- c("psych", "reshape2", "igraph", "VennDiagram", "pheatmap")


for (i in install_package) {
  if (!i %in% a)
    BiocManager::install(i, update = F)
}

suppressPackageStartupMessages(library("psych"))
suppressPackageStartupMessages(library("reshape2"))
suppressPackageStartupMessages(library("igraph"))
suppressPackageStartupMessages(library("VennDiagram"))
suppressPackageStartupMessages(library("pheatmap"))
```

## Input files
```{r}
otu_abundance_file = "tax_5Family.txt"

vip_species = "vip_13family.txt"

output_prefix = "net_family_feather_"

correlation_threshold = 0

pvalue_threshold = 0.05 

cor_file = paste0(output_prefix, "_correlation.txt")
pvalue_file = paste0(output_prefix, "_pvalue.txt")
edge_file_txt = paste0(output_prefix, "_edge.txt")
node_file_txt = paste0(output_prefix, "_node.txt")

edge_file_csv = paste0(output_prefix, "_edge.csv")
node_file_csv = paste0(output_prefix, "_node.csv")

degree_file = paste0(output_prefix, "_network_degree.txt")


VColor <- c("#636363","#78c679")
EColor <- c("#d7301f", "#0570b0")


table =read.table("tax_5Family.txt",header = T, row.names = 1)

table$full <- rownames(table)

library(tidyr)

table <- separate(table,full,
                        into=c("kindom", "phylum", "class", "order", "family"),
                      sep="\\|")
temp <- table
unassigned <- which(temp$family=="Unassigned")
temp$family[unassigned[1]] <- "Unassigned1"
temp$family[unassigned[2]] <- "Unassigned2"
temp$family[unassigned[3]] <- "Unassigned3"
temp$family[unassigned[4]] <- "Unassigned4"
temp$family[unassigned[5]] <- "Unassigned5"

rownames(temp) <- temp$family

temp <- temp[,1:152]

# Design of experiment
design = read.table("metadata.txt", header=T, row.names= 1, sep="\t") 

#group by skin, feather, oral, cloaca
design$group <- design$tissue
design$group[design$tissue%in%c("F", "G", "H", "I", "K", "L", "M")] <- "skin"
design$group[design$tissue%in%c("D", "E", "FY", "N")] <- "feather"
design$group[design$tissue=="B"] <- "oral"
design$group[design$tissue=="C"] <- "cloaca"


design <- design[design$tissue_type!="environement",]


design$group2 <- design$group
design$group2[design$tissue%in%c("F", "K", "L", "I")] <- "skin_feather"
design$group2[design$tissue%in%c("G", "M", "H")] <- "skin_nonfeather"


design_sub <- design[design$group=="feather",]

myData <-  temp[,rownames(design_sub)] 
```



## Correlation analysis

```{r}
cor <- cor(t(myData), method = "spearman")

p <- corr.test(t(myData), adjust="BH")  
pv <- p$p   


cor <- as.data.frame(cor)
pv <- as.data.frame(pv)
cor$family <- rownames(as.data.frame(cor))
pv$family <- rownames(pv)



cor[lower.tri(cor)] <- 0
pv[lower.tri(pv)] <- 0


pear.cor <- melt(cor, id.vars = "family")
pear.pv <- melt(pv, id.vars = "family")

pear <- data.frame(source = pear.cor[,1], target = pear.cor[,2], 
                   pearsonCor = pear.cor[,3], pearsonPV = pear.pv[,3])


pear.trim <- pear[-which(pear[,3] == "0"),]


pear.trim <- pear.trim[-which(pear.trim$source == pear.trim$target),]  

pear.trim$weight <- abs(as.vector(pear.trim[,3]))   

pear.trim$class <- 0  

pear.trim[which(pear.trim[,3] < 0),"class"] <- 2     #2 -> negative
pear.trim[which(pear.trim[,3] > 0),"class"] <- 1     #1 -> positive

pear.result <- pear.trim[which(pear.trim$weight > correlation_threshold),]     

pear.result <- pear.result[which(pear.result$pearsonPV < pvalue_threshold),]   
pear.result <- pear.result[,c(1,2,5,6)]


node <- myData


node.result <- data.frame(id = as.character(rownames(node)), weight = rowMeans(node), 
                          class = rep(1,length(node[,1])))



if(! is.null(vip_species)){
  vip_species_list <- read.table(vip_species, row.names=NULL, header=F)$V1
  node.result[which(node.result[,1] %in% vip_species_list), 3] <- 2
}

node.result
```

## Plots
```{r , echo=FALSE}
arcf <- pear.result

allnodes <- node.result
arc <- arcf[,1:2]
unodes <- unique(c(as.character(arc$source), as.character(arc$target)))    
node <- allnodes[allnodes$id %in% unodes,]


g <- graph.empty()
g <- graph_from_data_frame(arc,vertices = node)


nodeSize <- 0    
nodeDize <- 3
edgeSize <- 0
edgeDize <- 0.8

textSize <- 0.7
arrowSize <- 0



V(g)$size <- abs(nodeSize+nodeDize*log10(100*as.numeric(as.vector(node$weight))))
V(g)$color <- VColor[node$class]
V(g)$label.cex <- textSize
V(g)$frame.color <- "#252525"

E(g)$width <- edgeSize+2*(edgeDize*abs(as.numeric(as.vector(arcf$weight))))
E(g)$color <- EColor[arcf$class]
E(g)$arrow.size <- arrowSize

p <- plot(g,vertex.label.dist=0.6)
print(p)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


## save variables for following analysis
```{r}
g_feather <- g
arc_feather <- arc
node_feather <- node
p_feather <- p


save( arc_feather, node_feather,g_feather,p_feather,file=paste0(output_prefix, ".Rdata"))

```

